### ISSUE TITLE
Commit time distance after

### ISSUE THREAD

**Issue by idarav** [FrontEndART/project-kb#13]
Used to compute a feature reflecting the distance from a commit and the vulnerability publication data,
through comparing timestamps. The score is equal to 0.0 if the commit is before the release date,
and between 0.5 and 1.0 if the commit was after the vulnerability release.
The closer the commit is to the release, the higher the value.

**Comment by chicxurug** [comment]
Ez is jo, ez is menjen SAP issue-ba
