### ISSUE TITLE
AVG hunk size

### ISSUE THREAD

**Issue by idarav** [FrontEndART/project-kb#3]
Compute the average hunk size

**Comment by chicxurug** [comment]
Probaljuk meg, nem vagyok benne biztos, hogy ez is a feature extract-ba kell, bar a preprocess ugye csak a konkret hunk-okat adja meg, tehat ez mar feature kinyeres abbol. Szerintem akkor ezt vonjuk ossze a #2 -essel es legyen egy hunk related features SAP issue beloluk.

**Comment by idarav** [comment]
Merged.
